# Generated by Django 6.0.4 on 2026-04-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departamentos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caixa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ano",
                    models.PositiveIntegerField(
                        help_text="Ano de referência da caixa", verbose_name="Ano"
                    ),
                ),
                (
                    "mes",
                    models.PositiveIntegerField(
                        help_text="Mês de referência da caixa (1-12)",
                        verbose_name="Mês",
                    ),
                ),
                (
                    "numero_caixa",
                    models.PositiveIntegerField(
                        help_text="Número sequencial da caixa no período",
                        verbose_name="Número da Caixa",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        default="TEMP",
                        help_text="Código único de identificação (ex: DEP0001-MEM-2024-01-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Código da Caixa",
                    ),
                ),
                (
                    "capacidade_maxima",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Número máximo de documentos na caixa",
                        verbose_name="Capacidade Máxima",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Data de criação da caixa",
                        verbose_name="Data de Criação",
                    ),
                ),
                (
                    "data_fechamento",
                    models.DateField(
                        blank=True,
                        help_text="Data em que a caixa foi fechada",
                        null=True,
                        verbose_name="Data de Fechamento",
                    ),
                ),
                (
                    "localizacao_fisica",
                    models.CharField(
                        blank=True,
                        help_text="Localização física da caixa (ex: Estante A, Prateleira 3)",
                        max_length=100,
                        verbose_name="Localização Física",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre a caixa",
                        verbose_name="Observação",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ABERTA", "Aberta"),
                            ("FECHADA", "Fechada"),
                            ("EM_USO", "Em Uso"),
                            ("ARQUIVADA", "Arquivada"),
                        ],
                        default="ABERTA",
                        help_text="Status atual da caixa",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        help_text="Departamento responsável pela caixa",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="departamentos.departamento",
                        verbose_name="Departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caixa",
                "verbose_name_plural": "Caixas",
                "ordering": [
                    "departamento",
                    "tipo_documento",
                    "ano",
                    "mes",
                    "numero_caixa",
                ],
            },
        ),
    ]
