# Generated by Django 6.0.4 on 2026-04-10 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caixas", "0001_initial"),
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="caixa",
            name="tipo_documento",
            field=models.ForeignKey(
                help_text="Tipo de documento armazenado na caixa",
                on_delete=django.db.models.deletion.PROTECT,
                to="documentos.tipodocumento",
                verbose_name="Tipo de Documento",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="caixa",
            unique_together={
                ("departamento", "tipo_documento", "ano", "mes", "numero_caixa")
            },
        ),
    ]
