# Generated by Django 6.0.4 on 2026-04-13 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caixas", "0002_initial"),
        ("departamentos", "0001_initial"),
        ("documentos", "0005_remove_tipodocumento_nome_normalizado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caixa",
            options={
                "ordering": ["numero"],
                "verbose_name": "Caixa",
                "verbose_name_plural": "Caixas",
            },
        ),
        migrations.AlterUniqueTogether(
            name="caixa",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="caixa",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Descrição detalhada do conteúdo da caixa",
                verbose_name="Descrição",
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="nome",
            field=models.CharField(
                blank=True,
                help_text="Nome/descrição da caixa (será o mesmo do número por padrão)",
                max_length=100,
                verbose_name="Nome da Caixa",
            ),
        ),
        migrations.AddField(
            model_name="caixa",
            name="numero",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Número automático e único da caixa",
                verbose_name="Número da Caixa",
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="ano",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Ano de referência da caixa",
                null=True,
                verbose_name="Ano",
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="codigo",
            field=models.CharField(
                default="TEMP",
                help_text="Código único de identificação",
                max_length=50,
                unique=True,
                verbose_name="Código da Caixa",
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                help_text="Departamento responsável pela caixa",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="departamentos.departamento",
                verbose_name="Departamento",
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="localizacao_fisica",
            field=models.CharField(
                blank=True,
                help_text="Onde a caixa está fisicamente armazenada",
                max_length=100,
                verbose_name="Localização Física",
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="mes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Mês de referência da caixa (1-12)",
                null=True,
                verbose_name="Mês",
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="tipo_documento",
            field=models.ForeignKey(
                blank=True,
                help_text="Tipo principal de documento na caixa",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="documentos.tipodocumento",
                verbose_name="Tipo de Documento Principal",
            ),
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="data_criacao",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="data_fechamento",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="numero_caixa",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="observacao",
        ),
    ]
