# Generated by Django 6.0.4 on 2026-04-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caixas", "0003_alter_caixa_options_alter_caixa_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caixa",
            name="numero",
            field=models.PositiveIntegerField(
                help_text="Número automático e único da caixa",
                unique=True,
                verbose_name="Número da Caixa",
            ),
        ),
    ]
