# Generated by Django 6.0.4 on 2026-04-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caixas", "0004_alter_caixa_numero"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caixa",
            name="ano",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="capacidade_maxima",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="codigo",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="departamento",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="mes",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="status",
        ),
        migrations.RemoveField(
            model_name="caixa",
            name="tipo_documento",
        ),
    ]
