# Generated by Django 6.0.4 on 2026-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caixas", "0005_remove_caixa_ano_remove_caixa_capacidade_maxima_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="caixa",
            name="capacidade_maxima",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Número máximo de documentos na caixa (definido pelo cliente)",
                verbose_name="Capacidade Máxima",
            ),
        ),
    ]
