# Generated by Django 6.0.4 on 2026-04-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sigla",
                    models.CharField(
                        help_text="Sigla do departamento (ex: GAB, SECAD, SEFIN)",
                        max_length=10,
                        unique=True,
                        verbose_name="Sigla",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do departamento",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome do Departamento",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o departamento está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
                "ordering": ["sigla"],
            },
        ),
    ]
