# Generated by Django 6.0.4 on 2026-04-10 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caixas", "0001_initial"),
        ("departamentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do tipo de documento (ex: Lei, Portaria, Ofício)",
                        max_length=50,
                        unique=True,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Descrição do tipo de documento",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se o tipo está ativo",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do documento",
                        max_length=200,
                        verbose_name="Nome do Documento",
                    ),
                ),
                (
                    "assunto",
                    models.TextField(
                        help_text="Assunto ou resumo do documento",
                        verbose_name="Assunto",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        help_text="Número do documento (ex: 404/2024)",
                        max_length=50,
                        verbose_name="Número do Documento",
                    ),
                ),
                (
                    "ano_documento",
                    models.PositiveIntegerField(
                        help_text="Ano do documento", verbose_name="Ano do Documento"
                    ),
                ),
                (
                    "data_documento",
                    models.DateField(
                        help_text="Data de emissão do documento",
                        verbose_name="Data do Documento",
                    ),
                ),
                (
                    "arquivo_pdf",
                    models.FileField(
                        help_text="Arquivo PDF do documento digitalizado",
                        upload_to="documentos/%Y/%m/",
                        verbose_name="Arquivo PDF",
                    ),
                ),
                (
                    "texto_extraido",
                    models.TextField(
                        blank=True,
                        help_text="Texto extraído do documento via OCR",
                        verbose_name="Texto Extraído (OCR)",
                    ),
                ),
                (
                    "ocr_processado",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se o OCR já foi processado",
                        verbose_name="OCR Processado",
                    ),
                ),
                (
                    "palavra_chave",
                    models.CharField(
                        blank=True,
                        help_text="Palavras-chave para busca",
                        max_length=200,
                        verbose_name="Palavra-chave",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(
                        blank=True,
                        help_text="Observações adicionais sobre o documento",
                        verbose_name="Observação",
                    ),
                ),
                (
                    "data_upload",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "caixa",
                    models.ForeignKey(
                        help_text="Caixa onde o documento está armazenado",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="caixas.caixa",
                        verbose_name="Caixa",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        help_text="Departamento de origem",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="departamentos.departamento",
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        help_text="Tipo do documento",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="documentos.tipodocumento",
                        verbose_name="Tipo de Documento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["-data_documento", "numero_documento"],
            },
        ),
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CRIADO", "Documento Criado"),
                            ("ATUALIZADO", "Documento Atualizado"),
                            ("EXCLUIDO", "Documento Excluído"),
                            ("VISUALIZADO", "Documento Visualizado"),
                            ("BAIXADO", "Documento Baixado"),
                        ],
                        max_length=50,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(
                        help_text="Descrição detalhada da ação",
                        verbose_name="Descrição",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data e Hora"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documentos.documento",
                        verbose_name="Documento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["numero_documento", "ano_documento"],
                name="documentos__numero__89b765_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["tipo_documento"], name="documentos__tipo_do_7b089c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["departamento"], name="documentos__departa_ffe29d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(fields=["caixa"], name="documentos__caixa_i_289cb9_idx"),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["data_documento"], name="documentos__data_do_2a52ab_idx"
            ),
        ),
    ]
