# Generated by Django 6.0.4 on 2026-04-10 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caixas", "0002_initial"),
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="caixa",
            field=models.ForeignKey(
                blank=True,
                help_text="Caixa onde o documento está armazenado (opcional)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="caixas.caixa",
                verbose_name="Caixa",
            ),
        ),
    ]
