# Generated by Django 6.0.4 on 2026-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caixas", "0002_initial"),
        ("departamentos", "0001_initial"),
        ("documentos", "0002_alter_documento_caixa"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="documento",
            name="documentos__numero__89b765_idx",
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(
                fields=["numero_documento"], name="documentos__numero__3e0bd9_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="documento",
            name="ano_documento",
        ),
    ]
