# Generated by Django 6.0.4 on 2026-04-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0003_remove_documento_documentos__numero__89b765_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipodocumento",
            name="nome_normalizado",
            field=models.CharField(
                blank=True,
                help_text="Nome normalizado para busca e comparação",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Nome Normalizado",
            ),
        ),
    ]
