# Generated by Django 6.0.4 on 2026-04-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0004_tipodocumento_nome_normalizado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tipodocumento",
            name="nome_normalizado",
        ),
    ]
