# Generated by Django 6.0.4 on 2026-04-30 15:19

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoRetencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_operacao",
                    models.CharField(
                        choices=[
                            ("AUTH", "Autenticação"),
                            ("CREATE", "Criação"),
                            ("UPDATE", "Atualização"),
                            ("DELETE", "Exclusão"),
                            ("VIEW", "Visualização"),
                            ("DOWNLOAD", "Download"),
                            ("UPLOAD", "Upload"),
                            ("SEARCH", "Busca"),
                            ("EXPORT", "Exportação"),
                            ("BACKUP", "Backup"),
                            ("RESTORE", "Restauração"),
                            ("SECURITY", "Segurança"),
                            ("SYSTEM", "Sistema"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("dias_retencao", models.IntegerField(default=365)),
                (
                    "nivel_severidade_minimo",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Informação"),
                            ("WARNING", "Aviso"),
                            ("ERROR", "Erro"),
                            ("CRITICAL", "Crítico"),
                        ],
                        default="DEBUG",
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Configuração de Retenção",
                "verbose_name_plural": "Configurações de Retenção",
                "db_table": "auditoria_configuracao_retencao",
            },
        ),
        migrations.CreateModel(
            name="EstatisticaAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(db_index=True)),
                (
                    "tipo_operacao",
                    models.CharField(
                        choices=[
                            ("AUTH", "Autenticação"),
                            ("CREATE", "Criação"),
                            ("UPDATE", "Atualização"),
                            ("DELETE", "Exclusão"),
                            ("VIEW", "Visualização"),
                            ("DOWNLOAD", "Download"),
                            ("UPLOAD", "Upload"),
                            ("SEARCH", "Busca"),
                            ("EXPORT", "Exportação"),
                            ("BACKUP", "Backup"),
                            ("RESTORE", "Restauração"),
                            ("SECURITY", "Segurança"),
                            ("SYSTEM", "Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nivel_severidade",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Informação"),
                            ("WARNING", "Aviso"),
                            ("ERROR", "Erro"),
                            ("CRITICAL", "Crítico"),
                        ],
                        max_length=10,
                    ),
                ),
                ("total_registros", models.IntegerField(default=0)),
                ("usuarios_unicos", models.IntegerField(default=0)),
                ("ip_unicos", models.IntegerField(default=0)),
                ("falhas", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Estatística de Auditoria",
                "verbose_name_plural": "Estatísticas de Auditoria",
                "db_table": "auditoria_estatisticas",
                "ordering": ["-data", "tipo_operacao"],
                "unique_together": {("data", "tipo_operacao", "nivel_severidade")},
            },
        ),
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "nivel_severidade",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Informação"),
                            ("WARNING", "Aviso"),
                            ("ERROR", "Erro"),
                            ("CRITICAL", "Crítico"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "tipo_operacao",
                    models.CharField(
                        choices=[
                            ("AUTH", "Autenticação"),
                            ("CREATE", "Criação"),
                            ("UPDATE", "Atualização"),
                            ("DELETE", "Exclusão"),
                            ("VIEW", "Visualização"),
                            ("DOWNLOAD", "Download"),
                            ("UPLOAD", "Upload"),
                            ("SEARCH", "Busca"),
                            ("EXPORT", "Exportação"),
                            ("BACKUP", "Backup"),
                            ("RESTORE", "Restauração"),
                            ("SECURITY", "Segurança"),
                            ("SYSTEM", "Sistema"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("nome_usuario", models.CharField(blank=True, max_length=150)),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("modulo", models.CharField(db_index=True, max_length=100)),
                ("modelo", models.CharField(blank=True, max_length=100)),
                (
                    "objeto_id",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("objeto_repr", models.CharField(blank=True, max_length=255)),
                ("acao", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "dados_antes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "dados_depois",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                (
                    "metadados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                    ),
                ),
                ("hash_dados", models.CharField(max_length=64, unique=True)),
                ("checksum_verificado", models.BooleanField(default=False)),
                (
                    "sessao_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("duracao_ms", models.IntegerField(blank=True, null=True)),
                ("sucesso", models.BooleanField(default=True)),
                ("erro_msg", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_auditoria",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "db_table": "auditoria_log",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AlertaSeguranca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "tipo_alerta",
                    models.CharField(
                        choices=[
                            ("MULTIPLAS_FALHAS_LOGIN", "Múltiplas falhas de login"),
                            ("ACESSO_NEGADO", "Acesso negado recorrente"),
                            ("ATIVIDADE_SUSPEITA", "Atividade suspeita"),
                            ("ALTERACAO_MASSIVA", "Alteração massiva de dados"),
                            ("HORARIO_INCOMUM", "Acesso em horário incomum"),
                            ("IP_SUSPEITO", "Acesso de IP suspeito"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "nivel_alerta",
                    models.CharField(
                        choices=[
                            ("BAIXO", "Baixo"),
                            ("MEDIO", "Médio"),
                            ("ALTO", "Alto"),
                            ("CRITICO", "Crítico"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("dados_adicionais", models.JSONField(blank=True, default=dict)),
                ("visualizado", models.BooleanField(default=False)),
                ("visualizado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_visualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "logs_relacionados",
                    models.ManyToManyField(
                        blank=True, related_name="alertas", to="auditoria.logauditoria"
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Segurança",
                "verbose_name_plural": "Alertas de Segurança",
                "db_table": "auditoria_alerta_seguranca",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["timestamp", "nivel_severidade"],
                name="auditoria_l_timesta_aa9760_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["usuario", "timestamp"], name="auditoria_l_usuario_acae42_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["modulo", "tipo_operacao"], name="auditoria_l_modulo_2b27d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logauditoria",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="auditoria_l_ip_addr_5a63bb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertaseguranca",
            index=models.Index(
                fields=["timestamp", "nivel_alerta"],
                name="auditoria_a_timesta_112a5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertaseguranca",
            index=models.Index(
                fields=["visualizado", "timestamp"],
                name="auditoria_a_visuali_99b249_idx",
            ),
        ),
    ]
